version: '3'

vars:
  GIT_VERSION:
    sh: git describe --always --tags --dirty || echo "unknown"
  GIT_COMMIT:
    sh: git rev-parse HEAD || echo "unknown"
  GIT_BRANCH:
    sh: git branch --show-current || echo ""
  GIT_LAST_TAG:
    sh: git describe --tags --abbrev=0 || echo ""
  MODULE:
    sh: go mod edit -print | awk '/^module/ {print $2}'
  LD: "-s -X main.version={{.GIT_VERSION}} -X main.commit={{.GIT_COMMIT}} -X 'main.date={{now | date \"02.01.2006 15:04\"}}'"
  L: "{{\"{{\"}}"
  R: "{{\"}}\"}}"

tasks:
  default:
    cmds:
      - task: precommit

  tools:
    desc: Install development tools
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest

  clean:
    desc: Clean dist directory
    cmds:
      - mkdir -p dist
      - rm -rf dist/* || true

  deps:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  update:
    desc: Update dependencies
    cmds:
      - rm go.sum
      - go get -u ./...
      - go mod tidy

  test:
    desc: Run tests
    deps: [ deps ]
    cmds:
      - go test ./...

  test:verbose:
    desc: Run tests
    deps: [ deps ]
    cmds:
      - SQL_DEBUG=1 go test -v ./...

  build:
    desc: Build the application
    deps: [ clean, deps ]
    cmds:
      - go build -ldflags "{{.LD}}" -o dist/ ./cmd/...

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  lint:new:
    desc: Run golangci-lint on new changes
    cmds:
      - cmd: golangci-lint run ./... --new-from-rev $(git rev-parse HEAD^^^)
        if: '{{eq .GIT_BRANCH "master"}}'
      - cmd: golangci-lint run ./... --new-from-rev $(git rev-parse master)
        if: '{{ne .GIT_BRANCH "master"}}'

  format:
    desc: Format code
    cmds:
      - gofmt -s -w .
      - goimports -w -local={{.MODULE}} .

  precommit:
    deps: [ clean, deps, format ]
    cmds:
      - task: test
      - task: lint:new

  gox:
    desc: Cross-compile for multiple platforms
    deps: [ clean, deps ]
    cmds:
      - GOARM=6 gox --osarch="linux/amd64 darwin/arm64" -output 'dist/{{.L}}.OS{{.R}}_{{.L}}.Arch{{.R}}/{{.L}}.Dir{{.R}}' -ldflags "{{.LD}}" ./cmd/...
